### ISSUE TITLE
changes to the chain to match mauve's logic (mvp)

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-substrate#22]
- register a role (=offer the service) (Encoder, Attestor, Hoster) => list for each role
- publishData
---
Problem: 
- registerHoster has the logic to assign the hypercore to the newly registered Hoster -> but how do we now also asign the hypercore to the encoder??
- we should instead emit event (selected encoders & selected hosters)
---
Solution?
- additional logic in RegisterHoster/Register Encoder/Publish data
- each hypercore would have a count of how many hosters/encoder are available 
- when new registerHoster or registerEncoder we check if count_Encoder  >= min && count_Hoster >= min (min = 3) => then emit event (newHostingRequest)
- newHostingRequest emits 3 selected hosters and 3 selected encoders
---
- hoster triggers hosterReady(feedID, hoster pubKey) function
- chain emits event hosterReady
- publisher triggers Start a Challenge

**Comment by serapath** [comment]
function registerHoster (payload) {
  const id = saveHoster(payload)
  if (hasUnhostedFeeds()) emitHosting(id)
}

function publishData (payload) {
  const id = saveData(payload)
  if (hasAvailableHosters()) requestHosting(id)
}
```

**Comment by joshua-mir** [comment]
```
id => (hoster, archive, {State, Challenges})
```

where
``` 
enum State {
    
}

struct Challenges {

}
```
