### ISSUE TITLE
Getting started link?

### ISSUE THREAD

**Issue by martinheidegger** [playproject-io/datdot-substrate#31]
On the datdot-substrate landing page is a link to the getting started guide: https://substrate.dev/docs/en/overview/getting-started/ but it seems to result in a 404

**Comment by serapath** [comment]
@fionataeyang @ninabreznik - it's not high priority, but the correct link is obviously
* https://substrate.dev/docs/en/

So let's update it next time we touch the landing page

**Comment by serapath** [comment]
fixed @martinheidegger and thx :-)
